{
 "title": "game",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "gow",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperatures - gow",
     "type": "timeseries",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "ohm_cpu_celsius{job=\"prometheus.scrape.OhmGraphite\", hostname=\"gow\", sensor=~\"CPU Package|Core Average\"}",
       "legendFormat": "{{sensor}}"
      },
      {
       "expr": "ohm_gpunvidia_celsius{job=\"prometheus.scrape.OhmGraphite\", hostname=\"gow\"}",
       "legendFormat": "{{sensor}}"
      }
     ]
    },
    {
     "title": "Controls - gow",
     "type": "timeseries",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "ohm_superio_control_percent{job=\"prometheus.scrape.OhmGraphite\", hostname=\"gow\", sensor=\"Fan #2\"}",
       "legendFormat": "{{sensor}}"
      },
      {
       "expr": "ohm_gpunvidia_control_percent{job=\"prometheus.scrape.OhmGraphite\", hostname=\"gow\"}",
       "legendFormat": "{{sensor}}"
      }
     ]
    }
   ]
  },
  {
   "title": "iamd",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperatures - iamd",
     "type": "timeseries",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "ohm_cpu_celsius{job=\"prometheus.scrape.OhmGraphite\", hostname=\"iamd\"}",
       "legendFormat": "{{sensor}}"
      },
      {
       "expr": "ohm_gpunvidia_celsius{job=\"prometheus.scrape.OhmGraphite\", hostname=\"iamd\"}",
       "legendFormat": "{{sensor}}"
      }
     ]
    },
    {
     "title": "Controls - iamd",
     "type": "timeseries",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "ohm_superio_control_percent{job=\"prometheus.scrape.OhmGraphite\", hostname=\"iamd\"}",
       "legendFormat": "{{sensor}}"
      },
      {
       "expr": "ohm_gpunvidia_control_percent{job=\"prometheus.scrape.OhmGraphite\", hostname=\"iamd\"}",
       "legendFormat": "{{sensor}}"
      }
     ]
    }
   ]
  }
 ]
}