{
 "title": "node",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(node_cpu_seconds_total{job=\"integrations/unix\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "cpu",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"integrations/unix\", instance=\"$instance\", mode=\"idle\"}[1m]))) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{job=\"integrations/unix\", instance=\"$instance\"}[1m]))",
     "legendFormat": "transmit"
    },
    {
     "expr": "sum(irate(node_network_receive_bytes_total{job=\"integrations/unix\", instance=\"$instance\"}[1m]))",
     "legendFormat": "receive"
    }
   ]
  },
  {
   "title": "memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (instance) ((node_memory_MemTotal_bytes{job=\"integrations/unix\", instance=\"$instance\"} - node_memory_MemFree_bytes{job=\"integrations/unix\", instance=\"$instance\"}) / node_memory_MemTotal_bytes{job=\"integrations/unix\", instance=\"$instance\"}) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total{job=\"integrations/unix\", instance=\"$instance\"}[1m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(irate(node_disk_written_bytes_total{job=\"integrations/unix\", instance=\"$instance\"}[1m]))",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "cpu",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "cpu - core",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "1 - (avg by (cpu) (irate(node_cpu_seconds_total{job=\"integrations/unix\", instance=\"$instance\", mode=\"idle\"}[1m])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "cpu - mode",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg by (mode) (irate(node_cpu_seconds_total{job=\"integrations/unix\", instance=\"$instance\", mode!=\"idle\"}[1m])) ",
       "legendFormat": "{{mode}}"
      }
     ]
    }
   ]
  },
  {
   "title": "memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "memory - Mem",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{job=\"integrations/unix\", instance=\"$instance\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "node_memory_MemAvailable_bytes{job=\"integrations/unix\", instance=\"$instance\"}",
       "legendFormat": "Available"
      },
      {
       "expr": "node_memory_MemFree_bytes{job=\"integrations/unix\", instance=\"$instance\"}",
       "legendFormat": "Free"
      }
     ]
    },
    {
     "title": "memory - Swap",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_SwapTotal_bytes{job=\"integrations/unix\", instance=\"$instance\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "node_memory_SwapFree_bytes{job=\"integrations/unix\", instance=\"$instance\"}",
       "legendFormat": "Free"
      },
      {
       "expr": "node_memory_SwapCached_bytes{job=\"integrations/unix\", instance=\"$instance\"}",
       "legendFormat": "Cached"
      }
     ]
    },
    {
     "title": "memory - Active",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 155 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_Active_bytes{job=\"integrations/unix\", instance=\"$instance\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "node_memory_Active_anon_bytes{job=\"integrations/unix\", instance=\"$instance\"}",
       "legendFormat": "Anon"
      },
      {
       "expr": "node_memory_Active_file_bytes{job=\"integrations/unix\", instance=\"$instance\"}",
       "legendFormat": "File"
      }
     ]
    },
    {
     "title": "memory - Inactive",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 155 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_Inactive_bytes{job=\"integrations/unix\", instance=\"$instance\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "node_memory_Inactive_file_bytes{job=\"integrations/unix\", instance=\"$instance\"}",
       "legendFormat": "Anon"
      },
      {
       "expr": "node_memory_Inactive_anon_bytes{job=\"integrations/unix\", instance=\"$instance\"}",
       "legendFormat": "File"
      }
     ]
    }
   ]
  },
  {
   "title": "network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "network_transmit_bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "irate(node_network_transmit_bytes_total{job=\"integrations/unix\",instance=\"$instance\"}[1m])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "network_transmit_packets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "irate(node_network_transmit_packets_total{job=\"integrations/unix\", instance=\"$instance\"}[1m])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "network_receive_bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{job=\"integrations/unix\",instance=\"$instance\"}[1m])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "network_receive_packets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "irate(node_network_receive_packets_total{job=\"integrations/unix\", instance=\"$instance\"}[1m])",
       "legendFormat": "{{device}}"
      }
     ]
    }
   ]
  },
  {
   "title": "disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "disk_read_bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{job=\"integrations/unix\", instance=\"$instance\"}[1m])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "disk_reads_completed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(node_disk_reads_completed_total{job=\"integrations/unix\", instance=\"$instance\"}[1m])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "disk_written_bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "irate(node_disk_written_bytes_total{job=\"integrations/unix\", instance=\"$instance\"}[1m])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "disk_writes_completed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(node_disk_writes_completed_total{job=\"integrations/unix\", instance=\"$instance\"}[1m])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "filesystem used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{job=\"integrations/unix\", instance=\"$instance\"} - node_filesystem_avail_bytes{job=\"integrations/unix\", instance=\"$instance\", device!=\"tmpfs\"}",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "filesystem_avail",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_filesystem_avail_bytes{job=\"integrations/unix\", instance=\"$instance\", device!=\"tmpfs\"}",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "filefd_allocated",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_filefd_allocated{job=\"integrations/unix\", instance=\"$instance\"}",
       "legendFormat": "allocated"
      }
     ]
    },
    {
     "title": "filefd available",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_filefd_maximum{job=\"integrations/unix\", instance=\"$instance\"} - node_filefd_allocated{job=\"integrations/unix\", instance=\"$instance\"}",
       "legendFormat": "available"
      }
     ]
    }
   ]
  }
 ]
}