{
 "title": "nvidia_gpu",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "hostname",
    "query": {
     "query": "label_values(nvidia_smi_index,hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "utilization_gpu",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "nvidia_smi_utilization_gpu_ratio{job=\"prometheus.scrape.nvidia\", hostname=\"$hostname\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "utilization_memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "nvidia_smi_utilization_memory_ratio{job=\"prometheus.scrape.nvidia\", hostname=\"$hostname\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "temperature_gpu",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "nvidia_smi_temperature_gpu{job=\"prometheus.scrape.nvidia\", hostname=\"$hostname\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "memory_used",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nvidia_smi_memory_used_bytes{job=\"prometheus.scrape.nvidia\", hostname=\"$hostname\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "fan_speed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "nvidia_smi_fan_speed_ratio{job=\"prometheus.scrape.nvidia\", hostname=\"$hostname\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "clock_hz",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "nvidia_smi_clocks_current_graphics_clock_hz{job=\"prometheus.scrape.nvidia\", hostname=\"$hostname\"}",
     "legendFormat": "graphics"
    },
    {
     "expr": "nvidia_smi_clocks_current_video_clock_hz{job=\"prometheus.scrape.nvidia\", hostname=\"$hostname\"}",
     "legendFormat": "video"
    },
    {
     "expr": "nvidia_smi_clocks_current_sm_clock_hz{job=\"prometheus.scrape.nvidia\", hostname=\"$hostname\"}",
     "legendFormat": "sm"
    },
    {
     "expr": "nvidia_smi_clocks_current_memory_clock_hz{job=\"prometheus.scrape.nvidia\", hostname=\"$hostname\"}",
     "legendFormat": "memory"
    }
   ]
  },
  {
   "title": "clocks_event_reasons",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "nvidia_smi_clocks_event_reasons_applications_clocks_setting{job=\"prometheus.scrape.nvidia\", hostname=\"$hostname\"}",
     "legendFormat": "applications_clocks_setting"
    },
    {
     "expr": "nvidia_smi_clocks_event_reasons_gpu_idle{job=\"prometheus.scrape.nvidia\", hostname=\"$hostname\"}",
     "legendFormat": "gpu_idle"
    },
    {
     "expr": "nvidia_smi_clocks_event_reasons_hw_power_brake_slowdown{job=\"prometheus.scrape.nvidia\", hostname=\"$hostname\"}",
     "legendFormat": "hw_power_brake_slowdown"
    },
    {
     "expr": "nvidia_smi_clocks_event_reasons_hw_slowdown{job=\"prometheus.scrape.nvidia\", hostname=\"$hostname\"}",
     "legendFormat": "hw_slowdown"
    },
    {
     "expr": "nvidia_smi_clocks_event_reasons_hw_thermal_slowdown{job=\"prometheus.scrape.nvidia\", hostname=\"$hostname\"}",
     "legendFormat": "hw_thermal_slowdown"
    },
    {
     "expr": "nvidia_smi_clocks_event_reasons_sw_power_cap{job=\"prometheus.scrape.nvidia\", hostname=\"$hostname\"}",
     "legendFormat": "sw_power_cap"
    },
    {
     "expr": "nvidia_smi_clocks_event_reasons_sw_thermal_slowdown{job=\"prometheus.scrape.nvidia\", hostname=\"$hostname\"}",
     "legendFormat": "sw_thermal_slowdown"
    },
    {
     "expr": "nvidia_smi_clocks_event_reasons_sync_boost{job=\"prometheus.scrape.nvidia\", hostname=\"$hostname\"}",
     "legendFormat": "sync_boost"
    }
   ]
  }
 ]
}