{
 "title": "windows_node",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(windows_cpu_time_total{job=\"integrations/windows\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "cpu",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(windows_cpu_time_total{job=\"integrations/windows\", instance=\"$instance\", mode=\"idle\"}[1m]))) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "network",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(windows_net_bytes_sent_total{job=\"integrations/windows\", instance=\"$instance\"}[1m]))",
     "legendFormat": "transmit"
    },
    {
     "expr": "sum(irate(windows_net_bytes_received_total{job=\"integrations/windows\", instance=\"$instance\"}[1m]))",
     "legendFormat": "receive"
    }
   ]
  },
  {
   "title": "memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (instance) ((windows_cs_physical_memory_bytes{job=\"integrations/windows\", instance=\"$instance\"} - windows_os_physical_memory_free_bytes{job=\"integrations/windows\", instance=\"$instance\"}) / windows_cs_physical_memory_bytes{job=\"integrations/windows\", instance=\"$instance\"}) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "disk",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(windows_logical_disk_read_bytes_total{job=\"integrations/windows\", instance=\"$instance\", volume!~\"HarddiskVolume.*\"}[1m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(irate(windows_logical_disk_write_bytes_total{job=\"integrations/windows\", instance=\"$instance\", volume!~\"HarddiskVolume.*\"}[1m]))",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "cpu",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "cpu - core",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "1 - (avg by (core) (irate(windows_cpu_time_total{job=\"integrations/windows\", instance=\"$instance\", mode=\"idle\"}[1m])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "cpu - mode",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg by (mode) (irate(windows_cpu_time_total{job=\"integrations/windows\", instance=\"$instance\", mode!=\"idle\"}[1m])) ",
       "legendFormat": "{{mode}}"
      }
     ]
    }
   ]
  },
  {
   "title": "memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "physical",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "windows_cs_physical_memory_bytes{job=\"integrations/windows\", instance=\"$instance\"}",
       "legendFormat": "cs_physical_memory"
      },
      {
       "expr": "windows_os_physical_memory_free_bytes{job=\"integrations/windows\", instance=\"$instance\"}",
       "legendFormat": "os_physical_memory_free"
      },
      {
       "expr": "windows_os_visible_memory_bytes{job=\"integrations/windows\", instance=\"$instance\"}",
       "legendFormat": "os_visible_memory"
      }
     ]
    },
    {
     "title": "paging",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "windows_os_paging_limit_bytes{job=\"integrations/windows\", instance=\"$instance\"}",
       "legendFormat": "os_paging_limit"
      },
      {
       "expr": "windows_os_paging_free_bytes{job=\"integrations/windows\", instance=\"$instance\"}",
       "legendFormat": "os_paging_free"
      }
     ]
    },
    {
     "title": "virtual",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "windows_os_virtual_memory_bytes{job=\"integrations/windows\", instance=\"$instance\"}",
       "legendFormat": "os_virtual_memory"
      },
      {
       "expr": "windows_os_virtual_memory_free_bytes{job=\"integrations/windows\", instance=\"$instance\"}",
       "legendFormat": "os_virtual_memory_free"
      }
     ]
    },
    {
     "title": "process",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "windows_os_process_memory_limit_bytes{job=\"integrations/windows\", instance=\"$instance\"}",
       "legendFormat": "os_process_memory_limit"
      }
     ]
    }
   ]
  },
  {
   "title": "network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "net_bytes_sent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "irate(windows_net_bytes_sent_total{job=\"integrations/windows\",instance=\"$instance\"}[1m])",
       "legendFormat": "{{nic}}"
      }
     ]
    },
    {
     "title": "net_packets_sent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "irate(windows_net_packets_sent_total{job=\"integrations/windows\", instance=\"$instance\"}[1m])",
       "legendFormat": "{{nic}}"
      }
     ]
    },
    {
     "title": "net_bytes_received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "irate(windows_net_bytes_received_total{job=\"integrations/windows\",instance=\"$instance\"}[1m])",
       "legendFormat": "{{nic}}"
      }
     ]
    },
    {
     "title": "net_packets_received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "irate(windows_net_packets_received_total{job=\"integrations/windows\", instance=\"$instance\"}[1m])",
       "legendFormat": "{{nic}}"
      }
     ]
    }
   ]
  },
  {
   "title": "disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "reads",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(windows_logical_disk_reads_total{job=\"integrations/windows\", instance=\"$instance\", volume!~\"HarddiskVolume.*\"}[1m])",
       "legendFormat": "{{volume}}"
      }
     ]
    },
    {
     "title": "writes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(windows_logical_disk_writes_total{job=\"integrations/windows\", instance=\"$instance\", volume!~\"HarddiskVolume.*\"}[1m])",
       "legendFormat": "{{volume}}"
      }
     ]
    },
    {
     "title": "read_bytes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "irate(windows_logical_disk_read_bytes_total{job=\"integrations/windows\", instance=\"$instance\", volume!~\"HarddiskVolume.*\"}[1m])",
       "legendFormat": "{{volume}}"
      }
     ]
    },
    {
     "title": "write_bytes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "irate(windows_logical_disk_write_bytes_total{job=\"integrations/windows\", instance=\"$instance\", volume!~\"HarddiskVolume.*\"}[1m])",
       "legendFormat": "{{volume}}"
      }
     ]
    },
    {
     "title": "read_seconds",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(windows_logical_disk_read_seconds_total{job=\"integrations/windows\", instance=\"$instance\", volume!~\"HarddiskVolume.*\"}[1m])",
       "legendFormat": "{{volume}}"
      }
     ]
    },
    {
     "title": "write_seconds",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(windows_logical_disk_write_seconds_total{job=\"integrations/windows\", instance=\"$instance\", volume!~\"HarddiskVolume.*\"}[1m])",
       "legendFormat": "{{volume}}"
      }
     ]
    },
    {
     "title": "used",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "windows_logical_disk_size_bytes{job=\"integrations/windows\", instance=\"$instance\", volume!~\"HarddiskVolume.*\"} - windows_logical_disk_free_bytes{job=\"integrations/windows\", instance=\"$instance\", volume!~\"HarddiskVolume.*\"}",
       "legendFormat": "{{volume}}"
      }
     ]
    },
    {
     "title": "free",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "windows_logical_disk_free_bytes{job=\"integrations/windows\", instance=\"$instance\", volume!~\"HarddiskVolume.*\"}",
       "legendFormat": "{{volume}}"
      }
     ]
    }
   ]
  }
 ]
}